var Constants={PlayerStatus:{PLAYER_FLAG_A:0,PLAYER_FLAG_B:1},ReceiptType:{RECEIPT_TYPE_MATCH:"b",RECEIPT_TYPE_GAME:"c",RECEIPT_TYPE_SETTLE:"d"},MessageForPlayer:{PLAYER_READY_OVER:"PRO"},ReceiptStatus:{ROOM_STATUS_SUCCESS:"rs",GAME_BALL_TIME:"bt",CLEAR_BRICK_TO_A:"ca",CLEAR_BRICK_TO_B:"cb",MOVE_BAN:"mb",RECEIPT_STATUS_SUCCESS:"s",RECEIPT_STATUS_FALSE:"f"},GameParameter:{GAME_WIN_A:0,GAME_WIN_B:1,GAME_GRAW:2}},ws,url="chua.clvstudio.cn"+ctx;
window.onload=function(){ws="WebSocket"in window?new WebSocket("ws://"+url+"/webSocketServer"):"MozWebSocket"in window?new MozWebSocket("ws://"+url+"/webSocketServer"):new SockJS("http://"+url+"/sockjs/webSocketServer");ws.onopen=function(a){$(".logger").html("\u6210\u529f\u8fde\u63a5");ws.send('{t: "b", c: ""}')};ws.onmessage=function(a){eval("obj="+event.data);obj.t==Constants.ReceiptType.RECEIPT_TYPE_MATCH?obj.s==Constants.ReceiptStatus.ROOM_STATUS_SUCCESS&&($("#match").css("display","none"),$("#game").css("display",
"block"),game(ws,obj.msg),ws.send('{t: "'+Constants.ReceiptType.RECEIPT_TYPE_GAME+'", c: "'+Constants.MessageForPlayer.PLAYER_READY_OVER+'"}')):obj.t==Constants.ReceiptType.RECEIPT_TYPE_GAME?obj.s==Constants.ReceiptStatus.MOVE_BAN?(a=parseFloat(obj.msg),realBan(a)):obj.s==Constants.ReceiptStatus.GAME_BALL_TIME?realGameOfTime(obj.msg):obj.s==Constants.ReceiptStatus.CLEAR_BRICK_TO_B?realBrick(obj.msg,1):obj.s==Constants.ReceiptStatus.CLEAR_BRICK_TO_A&&realBrick(obj.msg,0):obj.t==Constants.ReceiptType.RECEIPT_TYPE_SETTLE&&
obj.s==Constants.ReceiptStatus.RECEIPT_STATUS_SUCCESS&&gameOver(obj.msg)};ws.onerror=function(a){};ws.onclose=function(a){}};var origin_x=0,origin_y=0,width,height,flag,ball_diameter;
function game(a,c){var b=$(window).width(),d=$(window).height();init(b,d);flag=c;b=document;b.addEventListener("touchstart",function(a){f=a.touches[0].pageX},!1);b.addEventListener("touchmove",function(b){e=b.touches[0].pageX;b=parseInt($(".myBan").css("left").replace(/px/g,""));b+=e-f;b=b<origin_x?origin_x:b+width/4>origin_x+width?origin_x+3*width/4:b;f=e;$(".airBan").css("left");$(".myBan").css("left",b);b=(b-origin_x)/width;a.send('{t: "c", c: "'+b+'"}')},!1);b.addEventListener("touchend",function(a){},
!1);var f,e;return width}function gameOver(a){window.location.href=ctx+"/settle?wol="+(flag==a.winFlag?"win":"lost")+"&score="+(flag==Constants.PlayerStatus.PLAYER_FLAG_A?""+a.scoreA+" : "+a.scoreB:""+a.scoreB+" : "+a.scoreA)}function realBan(a){a=1E4*a*width/1E4+origin_x;$(".airBan").css("left",a)}
function realBrick(a,c){flag==c?a.cb.forEach(function(a){$("#"+(a+36)+"").remove()}):a.cb.forEach(function(a){$("#"+a+"").remove()});flag==Constants.PlayerStatus.PLAYER_FLAG_A?$(document).attr("title","\u6bd4\u5206 "+a.sa+" \uff1a "+a.sb):$(document).attr("title","\u6bd4\u5206 "+a.sb+" \uff1a "+a.sa)}
function realGameOfTime(a){$("#time").text(a.time);flag!=Constants.PlayerStatus.PLAYER_FLAG_A&&(a.ballY=1-a.ballY);$(".ball").css({top:origin_y+a.ballY*height-ball_diameter/2,left:origin_x+a.ballX*width-ball_diameter/2})}function init(a,c){interfaceInit(a,c);initBang(width,height);initBricks(width,height);initBall(width,height);$(document).attr("title","\u6bd4\u5206 0 \uff1a 0")}
function initBall(){ball_diameter=32*height/1E3;$(".ball").css({width:32*height/1E3,top:origin_y+468*height/1E3,left:origin_x});$(".ball").css("display","block")}
function initBricks(){for(var a=width/9,c=.6*a,b="",d=0,f=0,e=0;4>e;d++,f++){var h=f+36,k=height-(e+1)*c,g=origin_x+d*a;b+='<div id="'+f+'" class="bricks" style="top:'+(origin_y+e*c)+"px;left:"+g+"px;width:"+a+"px;height:"+c+'px"> </div>';b+='<div id="'+h+'" class="bricks" style="top:'+k+"px;left:"+g+"px;width:"+a+"px;height:"+c+'px"> </div>';8<=d&&(d=-1,e++)}$("#Main").append(b)}
function initBang(){var a=width/4,c=.03*height;$(".myBan").css({width:a,height:c,top:origin_y+.688*height,left:origin_x+3*width/8});$(".airBan").css({width:a,height:c,top:origin_y+.282*height,left:origin_x+3*width/8})}
function interfaceInit(a,c){width=c/16*9;height=c;if(width<a){var b=(a-width)/2;origin_x=b;$("#Main").css({height:c,width:width,"margin-left":b})}else if(height=a/9*16,height<c){width=a;var d=(c-height)/2;origin_y=d;$("#Main").css({height:height,width:a,"margin-top":d})}else{b=.95;do height*=b,width=height/16*9,b-=.05;while(width>a&&height>c);b=(a-width)/2;d=(c-height)/2;origin_x=b;origin_y=d;$("#Main").css({height:c,width:width,"margin-left":b,"margin-top":d})}b=height/20;$(".vs").css({width:b,top:origin_y+
height/2-b/1.5,left:origin_x+width-b-.4*b});$("#myName").css({top:origin_y+height/2+1.5*b,left:origin_x+width-b-.4*b});$("#airName").css({top:origin_y+height/2-1.5*b-$("#airName").height(),left:origin_x+width-b-.4*b});$("#time").css({top:origin_y+height/2-$("#time").height()/2,left:origin_x+.4*b});return[width,height]};